import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Tables } from '@/integrations/supabase/types';
import { useLocation, useParams } from 'react-router-dom';
import { deepMerge } from '@/lib/utils'; // Importar deepMerge

type PlatformSettings = Tables<'platform_settings'>;

const DEFAULT_FONT_FAMILY = 'Inter, sans-serif';

// Function to generate default settings for a given memberAreaId
const getDefaultSettings = (memberAreaId: string, userId: string | null = null): PlatformSettings => ({
  id: '', // Will be generated by DB on insert
  user_id: userId,
  member_area_id: memberAreaId,
  logo_url: null,
  login_title: 'Bem-vindo à sua Área de Membros',
  login_subtitle: 'Acesse seu conteúdo exclusivo',
  global_font_family: 'Inter', // Default font
  colors: {
    background_login: '#F0F2F5', // Light beige/off-white
    card_login: '#FFFFFF',      // White
    header_background: '#FFFFFF', // White
    header_border: '#E5E7EB',   // Light gray
    button_background: '#E98B8B', // Pinkish-red from image
    text_primary: '#1F2937',    // Dark gray
    text_header: '#1F2937',     // Dark gray
    text_cards: '#1F2937',      // Dark gray
    text_secondary: '#6B7280',  // Medium gray
    checkmark_background: '#D1FAE5', // Light green for badge background
    checkmark_icon: '#059669',     // Darker green for checkmark icon
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
});

export const useGlobalPlatformSettings = () => {
  const location = useLocation();
  const { memberAreaId: urlMemberAreaId } = useParams<{ memberAreaId: string }>();

  const [settings, setSettings] = useState<PlatformSettings | null>(null);
  const [loadingSettings, setLoadingSettings] = useState(true);

  const fetchSettings = useCallback(async () => {
    setLoadingSettings(true);
    let currentMemberAreaId: string | null = null;

    // Tenta extrair memberAreaId da URL para páginas de área de membros
    if (location.pathname.startsWith('/membros/') && urlMemberAreaId) {
      currentMemberAreaId = urlMemberAreaId;
    } else if (location.pathname.startsWith('/admin/member-areas/') && urlMemberAreaId) {
      // Também para páginas de administração de área de membros, para o preview
      currentMemberAreaId = urlMemberAreaId;
    }

    if (currentMemberAreaId) {
      const { data, error } = await supabase
        .from('platform_settings')
        .select('*')
        .eq('member_area_id', currentMemberAreaId)
        .maybeSingle();

      if (error && error.code !== 'PGRST116') {
        console.error('Erro ao buscar configurações da plataforma:', error);
        setSettings(getDefaultSettings(currentMemberAreaId)); // Fallback para defaults
      } else if (data) {
        setSettings(deepMerge(getDefaultSettings(currentMemberAreaId), data as Partial<PlatformSettings>));
      } else {
        setSettings(getDefaultSettings(currentMemberAreaId)); // Use default if no settings found
      }
    } else {
      // Para páginas públicas ou se nenhum memberAreaId na URL, usa o padrão global (sem member_area_id)
      setSettings(null); // Ou um objeto de configurações globais se houver
    }
    setLoadingSettings(false);
  }, [location.pathname, urlMemberAreaId]);

  useEffect(() => {
    fetchSettings();
  }, [fetchSettings]);

  return {
    settings,
    loadingSettings,
  };
};