import React, { useState, useEffect } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Eye, EyeOff } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Tables } from '@/integrations/supabase/types';
import { deepMerge } from '@/lib/utils';
import { useToast } from '@/hooks/use-toast'; // Importar useToast

type PlatformSettings = Tables<'platform_settings'>;

// Function to generate default settings for a given memberAreaId
const getDefaultSettings = (memberAreaId: string): PlatformSettings => ({
  id: '', // Will be generated by DB on insert
  user_id: null,
  member_area_id: memberAreaId,
  logo_url: null,
  login_title: 'Bem-vindo à sua Área de Membros',
  login_subtitle: 'Acesse seu conteúdo exclusivo',
  global_font_family: 'Inter', // Default font
  colors: {
    background_login: '#F0F2F5', // Light beige/off-white
    card_login: '#FFFFFF',      // White
    header_background: '#FFFFFF', // White
    header_border: '#E5E7EB',   // Light gray
    button_background: '#E98B8B', // Pinkish-red from image
    text_primary: '#1F2937',    // Dark gray
    text_header: '#1F2937',     // Dark gray
    text_cards: '#1F2937',      // Dark gray
    text_secondary: '#6B7280',  // Medium gray
    checkmark_background: '#D1FAE5', // Light green for badge background
    checkmark_icon: '#059669',     // Darker green for checkmark icon
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
});

const MemberAreaLogin = () => {
  const { memberAreaId } = useParams<{ memberAreaId: string }>();
  const { signIn, user, isAdmin } = useAuth(); // Adicionado isAdmin
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [settings, setSettings] = useState<PlatformSettings | null>(null);
  const [loadingSettings, setLoadingSettings] = useState(true);
  const { toast } = useToast(); // Inicializado useToast

  useEffect(() => {
    const fetchSettings = async () => {
      if (!memberAreaId) {
        setLoadingSettings(false);
        return;
      }
      const { data, error } = await supabase
        .from('platform_settings')
        .select('*')
        .eq('member_area_id', memberAreaId)
        .maybeSingle();

      if (error && error.code !== 'PGRST116') {
        console.error('Error fetching platform settings:', error);
      } else if (data) {
        setSettings(deepMerge(getDefaultSettings(memberAreaId), data as Partial<PlatformSettings>));
      } else {
        setSettings(getDefaultSettings(memberAreaId));
      }
      setLoadingSettings(false);
    };

    fetchSettings();
  }, [memberAreaId]);

  // Redirect if already logged in and has access to this member area
  useEffect(() => {
    const checkAccessAndRedirect = async () => {
      if (user && memberAreaId) {
        // If the user is a global admin, they should go to their admin panel
        if (isAdmin) {
          navigate('/admin/member-areas', { replace: true });
          return;
        }

        // For regular members, check if their profile is linked to this member area
        const { data: profile, error: profileError } = await supabase
          .from('profiles')
          .select('member_area_id')
          .eq('user_id', user.id)
          .maybeSingle();

        if (profileError) {
          console.error('Error checking user profile for member area access:', profileError);
          toast({ title: "Erro de Acesso", description: "Não foi possível verificar seu acesso.", variant: "destructive" });
          // Stay on login page if there's an error checking profile
        } else if (profile?.member_area_id === memberAreaId) {
          navigate(`/membros/${memberAreaId}`, { replace: true }); // Redirect to dashboard if already logged in and has access
        } else {
          // User is logged in but does NOT have access to THIS member area
          toast({ title: "Acesso Negado", description: "Você não tem permissão para acessar esta área de membros.", variant: "destructive" });
          navigate('/', { replace: true }); // Redirect to home or generic access denied
        }
      }
    };
    checkAccessAndRedirect();
  }, [user, memberAreaId, navigate, isAdmin, toast]); // Adicionado isAdmin e toast às dependências

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    const { error } = await signIn(email, password);
    if (!error) {
      // On successful login, explicitly redirect to the member area dashboard
      // The useEffect above will handle the actual access check and final navigation
      navigate(`/membros/${memberAreaId}`, { replace: true });
    }
    setLoading(false);
  };

  if (loadingSettings) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  const currentSettings = settings || getDefaultSettings(memberAreaId || '');

  return (
    <div 
      className="min-h-screen flex items-center justify-center p-4"
      style={{ 
        backgroundColor: currentSettings.colors?.background_login || '#F0F2F5',
        fontFamily: currentSettings.global_font_family || 'Inter'
      }}
    >
      <Card className="w-full max-w-md" style={{ backgroundColor: currentSettings.colors?.card_login || '#FFFFFF' }}>
        <CardHeader className="text-center space-y-4">
          {currentSettings.logo_url && (
            <div className="mx-auto w-20 h-20 rounded-full flex items-center justify-center">
              <img 
                src={currentSettings.logo_url} 
                alt="Logo da Área de Membros" 
                className="w-20 h-20 object-contain animate-fade-in hover-scale"
              />
            </div>
          )}
          <div>
            <CardTitle className="text-2xl font-bold" style={{ color: currentSettings.colors?.text_primary || '#1F2937' }}>
              {currentSettings.login_title || 'Bem-vindo à sua Área de Membros'}
            </CardTitle>
            <CardDescription style={{ color: currentSettings.colors?.text_secondary || '#6B7280' }}>
              {currentSettings.login_subtitle || 'Acesse seu conteúdo exclusivo'}
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email" style={{ color: currentSettings.colors?.text_primary || '#1F2937' }}>Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="seu@email.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="password" style={{ color: currentSettings.colors?.text_primary || '#1F2937' }}>Senha</Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? 'text' : 'password'}
                  placeholder="Sua senha"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                  onClick={() => setShowPassword(!showPassword)}
                >
                  {showPassword ? (
                    <EyeOff className="h-4 w-4" style={{ color: currentSettings.colors?.text_secondary || '#6B7280' }} />
                  ) : (
                    <Eye className="h-4 w-4" style={{ color: currentSettings.colors?.text_secondary || '#6B7280' }} />
                  )}
                </Button>
              </div>
            </div>

            <Button 
              type="submit" 
              className="w-full" 
              disabled={loading}
              style={{ backgroundColor: currentSettings.colors?.button_background || '#E98B8B', color: '#FFFFFF' }} // Botão com texto branco
            >
              {loading ? 'Entrando...' : 'Entrar'}
            </Button>
          </form>

          <div className="mt-6 text-center">
            <p className="text-sm" style={{ color: currentSettings.colors?.text_secondary || '#6B7280' }}>
              Esqueceu sua senha?{' '}
              <Link to={`/auth/forgot-password?memberAreaId=${memberAreaId}`} className="hover:underline font-medium" style={{ color: currentSettings.colors?.button_background || '#E98B8B' }}>
                Recuperar senha
              </Link>
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default MemberAreaLogin;