import React, { useState, useEffect, useCallback } from 'react';
import { Navigate, useParams, Link } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client'; // Ainda usa o cliente principal para buscar settings e módulos
import { Tables } from '@/integrations/supabase/types';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Check, BookOpen, User, MessageSquare, ArrowRight } from 'lucide-react'; // Adicionado ArrowRight
import { deepMerge } from '@/lib/utils';
import { useMemberAreaAuth } from '@/hooks/useMemberAreaAuth'; // Usar o novo hook de autenticação

type PlatformSettings = Tables<'platform_settings'>;
type MemberArea = Tables<'member_areas'>;
type Module = Tables<'modules'>;

// Function to generate default settings for a given memberAreaId
const getDefaultSettings = (memberAreaId: string): PlatformSettings => ({
  id: '', // Will be generated by DB on insert
  user_id: null,
  member_area_id: memberAreaId,
  logo_url: null,
  login_title: 'Bem-vindo à sua Área de Membros',
  login_subtitle: 'Acesse seu conteúdo exclusivo',
  global_font_family: 'Inter', // Default font
  colors: {
    background_login: '#F0F2F5', // Light beige/off-white
    card_login: '#FFFFFF',      // White
    header_background: '#FFFFFF', // White
    header_border: '#E5E7EB',   // Light gray
    button_background: '#E98B8B', // Pinkish-red from image
    text_primary: '#1F2937',    // Dark gray
    text_header: '#1F2937',     // Dark gray
    text_cards: '#1F2937',      // Dark gray
    text_secondary: '#6B7280',  // Medium gray
    checkmark_background: '#D1FAE5', // Light green for badge background
    checkmark_icon: '#059669',     // Darker green for checkmark icon
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
});

const MemberAreaDashboard = () => {
  const { memberAreaId } = useParams<{ memberAreaId: string }>();
  const { user, loading: authLoading, signOut } = useMemberAreaAuth(); // Usar useMemberAreaAuth
  const { toast } = useToast();

  const [loading, setLoading] = useState(true);
  const [memberArea, setMemberArea] = useState<MemberArea | null>(null);
  const [modules, setModules] = useState<Module[]>([]);
  const [settings, setSettings] = useState<PlatformSettings | null>(null);
  const [hasAccess, setHasAccess] = useState(false);

  const fetchMemberAreaAndContent = useCallback(async () => {
    if (!memberAreaId || !user?.id) {
      setLoading(false);
      return;
    }

    setLoading(true);
    try {
      // 1. Fetch Member Area details
      const { data: areaData, error: areaError } = await supabase
        .from('member_areas')
        .select('*')
        .eq('id', memberAreaId)
        .maybeSingle();

      if (areaError || !areaData) {
        console.error('Error fetching member area:', areaError);
        toast({ title: "Erro", description: "Área de membros não encontrada.", variant: "destructive" });
        setHasAccess(false);
        setLoading(false);
        return;
      }
      setMemberArea(areaData);

      // 2. Fetch Platform Settings for this member area
      const { data: settingsData, error: settingsError } = await supabase
        .from('platform_settings')
        .select('*')
        .eq('member_area_id', memberAreaId)
        .maybeSingle();

      if (settingsError && settingsError.code !== 'PGRST116') {
        console.error('Error fetching platform settings:', settingsError);
      } else if (settingsData) {
        setSettings(deepMerge(getDefaultSettings(memberAreaId), settingsData as Partial<PlatformSettings>));
      } else {
        setSettings(getDefaultSettings(memberAreaId));
      }

      // 3. Check if user has access to this specific member area
      // Note: This check uses the main Supabase client to access the 'profiles' table,
      // as 'memberAreaSupabase' might not have the necessary RLS for 'profiles' directly.
      const { data: profileData, error: profileError } = await supabase
        .from('profiles')
        .select('member_area_id')
        .eq('user_id', user.id)
        .maybeSingle();

      if (profileError || profileData?.member_area_id !== memberAreaId) {
        setHasAccess(false);
        toast({ title: "Acesso Negado", description: "Você não tem permissão para acessar esta área de membros.", variant: "destructive" });
        setLoading(false);
        return;
      }
      setHasAccess(true);

      // 4. Fetch modules the user has access to
      const { data: modulesData, error: modulesError } = await supabase
        .from('modules')
        .select(`
          *,
          member_access!inner(user_id, is_active)
        `)
        .eq('member_area_id', memberAreaId)
        .eq('status', 'published')
        .eq('member_access.user_id', user.id)
        .eq('member_access.is_active', true)
        .order('order_index', { ascending: true });

      if (modulesError) {
        console.error('Error fetching user modules:', modulesError);
        toast({ title: "Erro", description: "Falha ao carregar seus módulos.", variant: "destructive" });
      } else {
        setModules(modulesData || []);
      }

    } catch (error: any) {
      console.error('Error in MemberAreaDashboard:', error);
      toast({ title: "Erro", description: error.message || "Ocorreu um erro ao carregar a área de membros.", variant: "destructive" });
      setHasAccess(false);
    } finally {
      setLoading(false);
    }
  }, [memberAreaId, user?.id, toast]);

  useEffect(() => {
    if (!authLoading) {
      if (!user) {
        // If not authenticated, redirect to login
        toast({ title: "Não autenticado", description: "Faça login para acessar a área de membros.", variant: "destructive" });
        return; // Prevent further execution until redirected
      }
      fetchMemberAreaAndContent();
    }
  }, [user, authLoading, fetchMemberAreaAndContent, toast]);

  if (authLoading || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (!user) {
    return <Navigate to={`/membros/${memberAreaId}/login`} replace />;
  }

  if (!hasAccess) {
    // If user is logged in but doesn't have access to this specific member area
    return (
      <div className="min-h-screen flex items-center justify-center p-4">
        <Card className="w-full max-w-md text-center">
          <CardHeader>
            <CardTitle>Acesso Negado</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>Você não tem permissão para acessar esta área de membros.</p>
            <Button onClick={() => signOut()}>Sair</Button>
            <Button asChild variant="outline">
              <Link to="/">Voltar para o Início</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const currentSettings = settings || getDefaultSettings(memberAreaId || '');
  const primaryColor = currentSettings.colors?.button_background || '#E98B8B';
  const textColor = currentSettings.colors?.text_primary || '#1F2937';
  const secondaryTextColor = currentSettings.colors?.text_secondary || '#6B7280';
  const cardBackground = currentSettings.colors?.card_login || '#FFFFFF';
  const fontFamily = currentSettings.global_font_family || 'Inter';
  const checkmarkBgColor = currentSettings.colors?.checkmark_background || '#D1FAE5';
  const checkmarkIconColor = currentSettings.colors?.checkmark_icon || '#059669';

  const userName = user?.user_metadata?.name || user?.email?.split('@')[0] || 'Membro';

  return (
    <div 
      className="w-full h-full flex flex-col overflow-auto p-4 min-h-screen" 
      style={{ 
        backgroundColor: currentSettings.colors?.background_login || '#F0F2F5',
        fontFamily: fontFamily 
      }}
    >
      {/* Header da Área de Membros */}
      <header 
        className="flex items-center justify-between p-4 mb-6 rounded-lg shadow-sm"
        style={{ 
          backgroundColor: currentSettings.colors?.header_background || '#FFFFFF',
          borderBottom: `1px solid ${currentSettings.colors?.header_border || '#E5E7EB'}`,
          color: currentSettings.colors?.text_header || '#1F2937'
        }}
      >
        <div className="flex items-center space-x-3">
          {memberArea?.logo_url && (
            <img 
              src={memberArea.logo_url} 
              alt={memberArea.name || "Logo"} 
              className="h-8 w-8 object-contain" 
            />
          )}
          <span className="text-lg font-semibold">{memberArea?.name || "Área de Membros RE-MÃE"}</span>
        </div>
        <Button onClick={signOut} variant="ghost" size="sm" style={{ color: secondaryTextColor }}>
          {user?.email?.charAt(0).toUpperCase() || 'E'}
        </Button>
      </header>

      {/* Conteúdo Principal */}
      <div className="flex-1 p-4 space-y-6">
        <h1 className="text-3xl font-bold" style={{ color: textColor }}>
          Olá, {userName}!
        </h1>
        <p className="text-lg" style={{ color: secondaryTextColor }}>
          Bem-vindo à sua área de membros. Escolha um módulo para começar.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {modules.length === 0 ? (
            <p className="text-muted-foreground">Nenhum módulo disponível para você ainda.</p>
          ) : (
            modules.map((module) => (
              <Card 
                key={module.id} 
                className="overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300"
                style={{ backgroundColor: cardBackground, color: currentSettings.colors?.text_cards || textColor }}
              >
                <div className="relative aspect-video w-full bg-gray-200">
                  {module.banner_url && (
                    <img 
                      src={module.banner_url} 
                      alt={module.title} 
                      className="w-full h-full object-cover" 
                    />
                  )}
                  {/* Placeholder para o badge de concluído - ajustar a lógica real depois */}
                  {module.title.includes('Boas-vindas') || module.title.includes('30 Dias') || module.title.includes('Exercícios') ? ( // Exemplo de condição
                    <div 
                      className="absolute top-4 right-4 p-2 rounded-full flex items-center justify-center"
                      style={{ backgroundColor: checkmarkBgColor }}
                    >
                      <Check className="h-5 w-5" style={{ color: checkmarkIconColor }} />
                    </div>
                  ) : null}
                </div>
                <CardContent className="p-6 space-y-4">
                  <h3 className="text-xl font-bold" style={{ color: currentSettings.colors?.text_cards || textColor }}>
                    {module.title}
                  </h3>
                  <p className="text-sm" style={{ color: secondaryTextColor }}>
                    {module.description}
                  </p>
                  <Button 
                    className="w-full flex items-center justify-center gap-2" 
                    style={{ backgroundColor: primaryColor, color: '#FFFFFF' }} // Botão com texto branco
                    asChild
                  >
                    <Link to={`/membros/${memberAreaId}/modules/${module.id}`}>
                      Acessar Módulo <ArrowRight className="h-4 w-4" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>
    </div>
  );
};

export default MemberAreaDashboard;